version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: lamp_stack
      MYSQL_DATABASE: competition
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: